import { PortfolioData } from './types'
import profilePhoto from '@/assets/images/zahid_passport_photo.png'

export const initialPortfolioData: PortfolioData = {
  name: 'Zahid Ahmed',
  title: 'Full Stack Software Engineer',
  tagline: 'C# | .NET | React | Angular | AWS — building scalable, cloud-native applications',
  photoUrl: profilePhoto,
  contact: {
    email: 'zahidbiscj@gmail.com',
    linkedin: 'https://www.linkedin.com/in/zahid-ahmed-b9859b73/',
    location: 'Malaysia',
    phone: '+60-11-68337220',
    github: 'https://github.com/zahidbiscj',
  },
  summary:
    "Full Stack .NET Developer with 6 years of professional experience in C#, ASP.NET 9, Angular, React, and JavaScript. Strong experience in cloud computing with AWS and Azure. My aim is to build my career as a software architect.",
  aboutMe:
    "I'm a Full Stack .NET developer with 6 years of professional experience in C#, ASP.NET 9, Angular, React, and JavaScript. I also have solid experience in cloud computing platforms like AWS and Azure. I enjoy working across the stack on complex business domains — from supply chain and healthcare to manufacturing — and my long-term goal is to grow into a software architect.",
  experiences: [
    {
      id: '1',
      title: 'Senior Full Stack .NET Developer',
      company: 'Roche Pharma Malaysia',
      location: 'Malaysia',
      startDate: 'June 2025',
      endDate: 'Present',
      description: 'Roche Microservice SCOT analysis — supply chain management system',
      companyType: 'Pharmaceutical',
      achievements: [
        'Working in the supply chain management system as a full-stack developer',
        'Implemented event-driven architecture using Apache Kafka and RabbitMQ',
        'Deploying and managing containerized applications using Kubernetes',
        'Maintained Jira and Azure DevOps, working with an agile approach and completing sprint planning',
      ],
      technologies: [
        '.NET 9',
        'Angular 20',
        'PostgreSQL',
        'Apache Kafka',
        'RabbitMQ',
        'xUnit',
        'Microservices',
        'Azure DevOps',
        'Playwright',
        'Python',
      ],
    },
    {
      id: '2',
      title: 'Software Engineer',
      company: 'Nifty Coders (IQVIA — Fortune 500)',
      location: 'Remote',
      startDate: 'March 2024',
      endDate: 'June 2025',
      description: 'IQVIA Healthcare data analytics',
      companyType: 'Healthcare',
      achievements: [
        'Maintained communication with onshore teams while collaborating with developers across remote locations',
        'Worked as a Full Stack .NET Developer on multiple projects',
        'Wrote unit tests and BDD tests to ensure code maintainability',
        'Worked with an agile approach and maintained Jira properly',
      ],
      technologies: [
        'Microservices',
        '.NET 8',
        'Angular 16',
        'PostgreSQL',
        'MongoDB',
        'Clean Architecture',
        'nUnit',
        'SpecFlow (BDD)',
        'AWS Lambda',
        'Docker',
        'EF Core',
        'LINQ',
        'Azure Logic Apps',
      ],
    },
    {
      id: '3',
      title: 'Software Engineer',
      company: 'Kaz Software',
      location: 'Dhaka, Bangladesh',
      startDate: 'August 2020',
      endDate: 'February 2024',
      description: 'UNICEF, HATIL (Manufacturing), Care MIS, Stakeholder management',
      companyType: 'Software Company',
      achievements: [
        'Contributed as a full-stack developer across complex business areas',
        'Led a team with an agile approach and interacted directly with the PM to manage projects',
        'Integrated 3D modeling using Three.js and implemented map integration via the OpenStreetMap API',
        'Used Node.js to create web jobs, retrieve data from external APIs, and trigger Lambda functions',
        'Provided technical support and mentorship to the full team',
        'Built automation tools with Python for manufacturing',
      ],
      technologies: [
        '.NET 7',
        'JavaScript',
        'React',
        'EF Core',
        'AWS Lambda',
        'AWS EventBridge',
        'Serverless',
        'Azure Service Bus',
        'Razor',
        'LINQ',
        'PWA',
        'Stored Procedures',
        'PowerApps',
        'Power Automate',
        'D365 CRM',
        'MSSQL',
      ],
    },
  ],
  education: [
    {
      id: '1',
      degree: 'B.Sc. in Computer Science and Engineering (CSE)',
      institution: 'Bangladesh University of Business & Technology (BUBT)',
      location: 'Dhaka, Bangladesh',
      startDate: '2016',
      endDate: '2020',
      description: 'Strong foundation in computer science fundamentals and software engineering.',
      gpa: '3.78 / 4.00',
    },
    {
      id: '2',
      degree: 'Higher Secondary Certificate (HSC)',
      institution: 'Milestone College',
      location: 'Dhaka, Bangladesh',
      startDate: '2013',
      endDate: '2015',
      description: 'Science group.',
      gpa: '4.56 / 5.00',
    },
    {
      id: '3',
      degree: 'Secondary School Certificate (SSC)',
      institution: 'Bangladesh International School and College',
      location: 'Jeddah, KSA',
      startDate: '2011',
      endDate: '2013',
      description: 'Science group.',
      gpa: '5.00 / 5.00',
    },
  ],
  skills: {
    backend: [
      { name: 'C#', proficiency: 95, yearsOfExperience: 6 },
      { name: '.NET 9', proficiency: 90, yearsOfExperience: 2 },
      { name: '.NET 6/8', proficiency: 92, yearsOfExperience: 4 },
      { name: '.NET Core 3.1', proficiency: 90, yearsOfExperience: 5 },
      { name: 'ASP.NET', proficiency: 92, yearsOfExperience: 6 },
      { name: 'Web API', proficiency: 92, yearsOfExperience: 6 },
      { name: 'Entity Framework Core', proficiency: 90, yearsOfExperience: 5 },
      { name: 'ADO.NET', proficiency: 82, yearsOfExperience: 5 },
      { name: 'CQRS / Mediator', proficiency: 82, yearsOfExperience: 4 },
      { name: 'SignalR', proficiency: 80, yearsOfExperience: 4 },
      { name: 'RabbitMQ / Kafka', proficiency: 82, yearsOfExperience: 2 },
      { name: 'LINQ', proficiency: 90, yearsOfExperience: 6 },
    ],
    frontend: [
      { name: 'Angular', proficiency: 88, yearsOfExperience: 5 },
      { name: 'React', proficiency: 85, yearsOfExperience: 4 },
      { name: 'JavaScript', proficiency: 88, yearsOfExperience: 6 },
      { name: 'TypeScript', proficiency: 85, yearsOfExperience: 4 },
      { name: 'Three.js', proficiency: 72, yearsOfExperience: 2 },
      { name: 'HTML5', proficiency: 92, yearsOfExperience: 6 },
      { name: 'CSS3', proficiency: 88, yearsOfExperience: 6 },
    ],
    cloud: [
      { name: 'AWS Lambda', proficiency: 85, yearsOfExperience: 4 },
      { name: 'AWS EventBridge', proficiency: 80, yearsOfExperience: 3 },
      { name: 'AWS SQS', proficiency: 78, yearsOfExperience: 3 },
      { name: 'AWS IAM', proficiency: 78, yearsOfExperience: 3 },
      { name: 'AWS S3 / SES / EC2', proficiency: 82, yearsOfExperience: 4 },
      { name: 'Azure Service Bus', proficiency: 80, yearsOfExperience: 3 },
      { name: 'Azure Functions', proficiency: 80, yearsOfExperience: 3 },
      { name: 'Azure Logic Apps', proficiency: 78, yearsOfExperience: 2 },
      { name: 'Azure DevOps', proficiency: 82, yearsOfExperience: 3 },
      { name: 'Kubernetes', proficiency: 75, yearsOfExperience: 1 },
    ],
    databases: [
      { name: 'MS SQL Server', proficiency: 92, yearsOfExperience: 6 },
      { name: 'PostgreSQL', proficiency: 85, yearsOfExperience: 3 },
      { name: 'MySQL', proficiency: 82, yearsOfExperience: 5 },
      { name: 'MongoDB', proficiency: 80, yearsOfExperience: 3 },
      { name: 'T-SQL / Stored Procedures', proficiency: 85, yearsOfExperience: 6 },
    ],
    testing: [
      { name: 'NUnit', proficiency: 85, yearsOfExperience: 5 },
      { name: 'xUnit', proficiency: 85, yearsOfExperience: 3 },
      { name: 'Moq', proficiency: 82, yearsOfExperience: 5 },
      { name: 'Shouldly', proficiency: 78, yearsOfExperience: 4 },
      { name: 'SpecFlow (BDD)', proficiency: 80, yearsOfExperience: 3 },
      { name: 'Playwright', proficiency: 78, yearsOfExperience: 1 },
      { name: 'Docker', proficiency: 78, yearsOfExperience: 3 },
      { name: 'Git', proficiency: 90, yearsOfExperience: 6 },
    ],
    tools: [
      { name: 'Visual Studio', proficiency: 95, yearsOfExperience: 6 },
      { name: 'VS Code', proficiency: 90, yearsOfExperience: 6 },
      { name: 'Jira', proficiency: 88, yearsOfExperience: 5 },
      { name: 'Azure DevOps', proficiency: 82, yearsOfExperience: 3 },
      { name: 'Git / SVN', proficiency: 88, yearsOfExperience: 6 },
      { name: 'Trello', proficiency: 80, yearsOfExperience: 4 },
      { name: 'Power Automate', proficiency: 75, yearsOfExperience: 2 },
    ],
    cms: [
      { name: 'NopCommerce', proficiency: 80, yearsOfExperience: 2 },
      { name: 'D365 CRM', proficiency: 72, yearsOfExperience: 2 },
    ],
    ai: [
      { name: 'Claude', proficiency: 82, yearsOfExperience: 1 },
      { name: 'Cursor', proficiency: 82, yearsOfExperience: 1 },
      { name: 'Codex', proficiency: 78, yearsOfExperience: 1 },
      { name: 'AI Prompt Engineering', proficiency: 80, yearsOfExperience: 1 },
      { name: 'Python Automation', proficiency: 78, yearsOfExperience: 2 },
    ],
  },
  projects: [
    {
      id: '1',
      name: 'IQVIA',
      url: 'https://www.iqvia.com/',
      description:
        'IQVIA is a clinical research organization. Architected and deployed highly scalable, event-driven microservices on the IQVIA platform using Kubernetes, Kafka, .NET, and Angular to process petabyte-scale healthcare datasets for global clinical intelligence.',
      status: 'Live',
      market: 'Global',
      technologies: ['.NET 8', 'Angular', 'Azure', 'Kubernetes', 'Kafka', 'Microservices'],
      features: [
        'Event-driven microservices',
        'Petabyte-scale healthcare data processing',
        'Kubernetes orchestration',
        'Global clinical intelligence',
      ],
    },
    {
      id: '2',
      name: 'HATIL Manufacturing',
      url: 'https://hatil.com',
      description:
        'HATIL is a fast-growing global furniture brand with customers around the globe, presenting an impeccable range of wooden furniture products manufactured from the best-sourced materials.',
      status: 'Live',
      market: 'Global',
      technologies: [
        '.NET 7',
        'Next.js',
        'NopCommerce',
        'AWS EventBridge',
        'AWS Lambda',
        'EF Core',
        'React',
        'LINQ',
      ],
      features: [
        'Full NopCommerce customization',
        'Manufacturing automation',
        'Cloud software infrastructure',
        'E-commerce platform',
      ],
    },
    {
      id: '3',
      name: 'UNICEF MIS',
      url: '#',
      description:
        "Built UNICEF's MIS education system to support Rohingya refugees. Refugee children living in Bangladesh camps receive education and other facilities through the app. It is mainly used for data collection, planning projects, and executing them on scheduled instances.",
      status: 'Completed',
      market: 'Bangladesh',
      technologies: [
        '.NET Core 3.1',
        'Angular 8',
        'PWA',
        'EF Core',
        'Onion Architecture',
        'Microfrontend',
        'SignalR',
        'MongoDB',
      ],
      features: [
        'Onion architecture with microfrontend',
        'JWT policy-based authorization',
        'Angular PWA with long polling & SignalR',
        'AWS SES, S3, EC2 integration',
      ],
    },
    {
      id: '4',
      name: 'Software Company Profile Listing',
      url: 'https://github.com/zahidbiscj/ProfileListingProject',
      description: 'A software company profile listing project built with C# and ASP.NET Core.',
      status: 'Open Source',
      market: 'Open Source',
      technologies: ['C#', 'ASP.NET Core'],
      features: ['Company profile listing', 'ASP.NET Core backend'],
    },
  ],
  certifications: [
    {
      id: '1',
      name: 'AWS Certified Cloud Practitioner (Score: 814)',
      issuer: 'Amazon Web Services',
      date: '',
    },
    {
      id: '2',
      name: 'AWS Cloud Quest: Cloud Practitioner (Digital Badge)',
      issuer: 'Amazon Web Services',
      date: '',
    },
  ],
  languages: [
    { name: 'English', proficiency: 'Professional Working Proficiency' },
    { name: 'Bengali', proficiency: 'Native' },
  ],
  stats: [
    { id: '1', label: 'Years Experience', value: '6+', icon: 'briefcase' },
    { id: '2', label: 'Projects Completed', value: '10+', icon: 'code' },
    { id: '3', label: 'Companies', value: '3', icon: 'rocket' },
    { id: '4', label: 'Technologies', value: '30+', icon: 'stack' },
  ],
  highlights: [
    'Implemented event-driven architecture using Apache Kafka and RabbitMQ at Roche',
    'Deployed and managed containerized applications using Kubernetes',
    'Architected event-driven microservices processing petabyte-scale healthcare data at IQVIA',
    'Integrated 3D modeling with Three.js and maps via the OpenStreetMap API',
    'Built Python automation tools for manufacturing workflows',
    'AWS Certified Cloud Practitioner — currently pursuing AWS Solution Architect & Azure Developer Associate',
  ],
}
